# Generated by Django 3.2.6 on 2021-09-10 00:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (0, 'Domingo')], default=1, max_length=1, verbose_name='Dia de la semana')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cp', models.IntegerField(verbose_name='Codigo Postal')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('nombre_os', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='Nombre Obra Social')),
                ('direccion', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('disponibilidad', models.BooleanField(verbose_name='Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('num_hc', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Historia Clinica')),
                ('num_os', models.CharField(max_length=150, verbose_name='Nunero Obra Social')),
                ('titular_familiar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titular Obra Social')),
                ('obra_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_obrasocial', to='odontologia.obrasocial')),
            ],
            options={
                'ordering': ['paciente', 'num_hc'],
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('num_doc', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero Documento')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('num_cuit', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero Cuit/Cuil')),
                ('fecha_nac', models.DateField(default=datetime.datetime, verbose_name='Fecha Nacimiento')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('direccion', models.CharField(max_length=150, verbose_name='Domicilio')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persona_localidad', to='odontologia.localidad')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de Matricula ')),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad ')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesional_persona', to='odontologia.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('password', models.CharField(max_length=15, verbose_name='Contraseña')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_persona', to='odontologia.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime, verbose_name='Fecha Turno')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado del turno')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_profesional', to='odontologia.profesional')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_paciente', to='odontologia.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente_persona', to='odontologia.personas'),
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del establecimiento')),
                ('razon_social', models.CharField(max_length=30, verbose_name='Razon social del establecimiento')),
                ('direccion', models.CharField(max_length=150, verbose_name='Domicilio establecimiento')),
                ('telefono', models.CharField(max_length=30, verbose_name='Numero de telefono')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email del establecimiento')),
                ('web', models.CharField(max_length=150, verbose_name='Web del establecimiento')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establecimiento_localidad', to='odontologia.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_hora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidad_calendario', to='odontologia.calendario')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidad_profesional', to='odontologia.profesional')),
            ],
        ),
    ]
